### PR TITLE
Added French translation

### PR DESCRIPTION
**Pull request by jej**
I created this French translation. Hope it helps. Cheers,
J.

### CODE REVIEW

**Comment by forrestguice** [comment]
Awesome, thank you. This will make a great addition.

**Comment by jej** [comment]
Thanks for the merge.
I had a problem with the layout of the table on the main screen. If I translate Rise/Set in French it is Lever/Coucher. But it stretches too much the table layout then the hours on the right are clipped. Maybe the pictures should be above texts to increase available width, or configure the layout of the table differently. It seems there is enough width to display everything.
So to solve quickly, I translated by Lev./Couch. Not very smart :)
J.

**Comment by jej** [comment]
This is what I mean: https://github.com/jej/SuntimesWidget/tree/Table-header-test

**Comment by forrestguice** [comment]
I see what you mean, there was a similar issue w/ the other translations (#43). That led to refactoring the layouts and moving a bunch of definitions to `values/table_res.xml`, with the idea being to provide alternate values as more space becomes available (`values-sw330dp/table_res.xml`). For tiny screens the text should ellipsize (so even if its not pretty all the info is still displayed), while for larger screens the table should stretch.

I'm looking at it now, and it doesn't seem like the `table_heading_label_maxems` value works very well w/ the `fr` strings - even when there is enough space it doesn't ellipse correctly. It doesn't starts to ellipsize the way I'd expect until I bump it up to 4 - I'm get "Couche" when there is obviously enough space for the final letter, very frustrating.

There are a couple solutions I think. 

We should be able to provide an alternate `table_res.xml` for the fr locale (similar to `strings.xml`) with values that work. There are a couple values we might change; fontsize, maxems, or allowing the text to spill over onto the next line. 

We can also provide alternate layouts for the fr locale. As you suggested we could change the orientation to `vertical` to get more space, or we could hide the icon entirely.

Here's what that might look like on a Nexus One (a 3.7" screen showing 480x800), maxems bumped up to 4, and the layout changes.

suntimes_headerissue0

Its a challenge because there are so many different screen configurations, and what looks good on a small screen doesn't look great on a larger one, and vice versa. I'll continue to play around with it.

**Comment by forrestguice** [comment]
whats your screen configuration when you see the hours clipped off at the right? it might be helpful to see a screenshot of the hours getting clipped off at the right - the labels should get mangled before thats allowed to happen :\

**Comment by jej** [comment]
Maybe the real solution is the ConstraintLayout!

But with the icons at top of the text I guess it solves easily the 
problem for most situations. And English remains Sunset/Sunrise instead 
of set/rise...

On my config the problem is emphased by the fact I use a "big" font (1 
step above the default font size). So evething is a bit bigger. I guess 
ConstraintLayout manage that.

J.

**Comment by forrestguice** [comment]
> Maybe the real solution is the ConstraintLayout!

I wasn't aware of this layout - I'm reading about it now and it does seem like a good solution. very clean. 

> On my config the problem is emphased by the fact I use a "big" font

aha. This is something I hadn't considered. I'll try and make a point of testing for it.
it makes sense that changing the font and other "accessibility" type settings would cause the current hack to break down.

for now I'll put a bandaid on it by tweaking the layout. That is probably what will be in next release (unless I find myself w/ some unexpected free time). My intention is to fix it though - a table that looks ok on all devices and locales w/out a mess of alt resources and edge cases.

**Comment by jej** [comment]
Le 03/05/2017 à 00:35, Forrest Guice a écrit :
>
>     Maybe the real solution is the ConstraintLayout!
>
> I wasn't aware of this layout - I'm reading about it now and it does 
> seem like a good solution. very clean.
>

You can convert your layouts to ConstraintLayout. Right-click in layout 
hierarchy -> Convert linear to contraint.

Most of the time it's not perfect but it's a start...

And then lot's of headache to built the full contraints' model :) but 
after that it works quite well and it's funny to play with different 
devices size and landscape/portray. It works almost alone.

J.

**Comment by forrestguice** [comment]
ConstraintLayout is nothing short of amazing! Thanks for letting me know, I think its my new favorite. 

I think #43 is actually fixed now - it looks consistent on all the devices I've tested. 
I will merge it all within the next week and tag a release.

**Comment by jej** [comment]
Yep, that's work perfectly for me now! Thanks a lot too, and enjoy with ConstraintLayouts :)

**Pull request merged**
