### PR TITLE
release 0.15.0

### LINKED ISSUE #345: the moon day
i need (1x1) widget show moon day -  to know what is the day of the moon is .
(small islamic calendar , just the day)

### LINKED ISSUE #384: Inconsistent moon illumination numbers
I noticed that the moon illumination percentage differs significantly between main screen and moon details:

Main screen says "1% illuminated" (in German):
Suntimes_20191224-205521

Detail screen says 2.2% illuminated (in German):
Suntimes_20191224-205531

Both screen shots were taken within a few seconds. Obviously one of the numbers cannot be correct.

### LINKED ISSUE #398: [feature request] Solar Hijiri Calendar
Hello, how feasible would it be to add a widget showing the date according to Solar Hijiri Calendar?

Here’s the definition:
1. First day of the year is after midnight between the two consecutive solar noons, which include the instant of the March equinox.
2. The first six months have 31 days. Their names are: Farvardin, Ordibehesht, Khordad, Tir, Mordad, Shahrivar
3. The last five months have 30 days. Their names are: Mehr, Aban, Azar, Dey, Bahman
4. The very last month (named Esfand) actually might be 29 days / 30 days, depending on leap years. No need to know when is a leap year, because the new year depends on March equinox!

Interestingly enough, these months correspond to zodiac signs, hence equinoxes and solstices occur on the 1st day of every third month. And thus, adding this feature is also a mean to display astrological signs!

Some reference: https://en.wikipedia.org/wiki/Solar_Hijri_calendar

### LINKED ISSUE #399: [feature request] Solar time in status bar
The Clock Widget already allows to display Solar time on the home screen, but what about the option to display Solar time in the status bar?

As a bonus, I figure it like this: in a persistent notification, with two lines of text, there is even enough space to display some additional info, e.g. user-selected Sun or Moon times.

### LINKED ISSUE #492: Quite a few custom theme settings not working
Thank you for the great app and for making it open source!

It's really wonderful, but I found many of the strings in the app to be too tiny to easily read.  Also, I found the contrast to be too low.  As such, I created a nice custom theme for it.

Unfortunately, many of the theme settings do not get applied, and others *appear* to not get applied because they require the app to be completely closed and restarted.

For example, the font size options appear to do nothing in the app.  Also the main background color does not change when the background color in a custom theme color is changed.

Things like settings for the color of the day/night bar in the bottom of the main screen do not become effective until the user forces the app the restart.  Also, the previews for that element do not reflect the colors specified in the custom theme.

I have some other constructive feedback as well, but please let me know if you have time to work on things or would prefer I hold off on other issue reports.

Overall, I find the app fantastic, but I need almost everything to be significantly larger to make use of it.  Allowing the main window to scroll vertically would be a big help in this regard too.

Thank you again for the wonderful app.

Tested v0.13.9 on Android 7.0

### LINKED ISSUE #522: Hoping for more detailed Notifications and offset by the degree of elevation of the sun
Hello Sir Forrest Guice, this is really a majorly great app already!  I really hope for more verbal and structured Notifications from then SunTimesWidget. Now it just says e.g. "Blue hour",  when it actually is: "30 minutes till the end of evening blue hour".  Another enhancement that I'm hoping is an option in addition of the time offset, the offset by the elevation degree of the sun (plus or minus) , so that e.g. "35 degrees past sunrise",  or "8 degrees till noon", or "11 degrees past noon" or would be possible, (for sunbathing purposes).  I hope for more verbal & structured  Notifications because the 'Voice Notify' app (from F-Droid) speaks the Notifications out loud (of apps selected by the user), the TTS message items in that app are the following: #a = App Title, #t =Ticker, #s = Subtext, #c = Content title, #m = Content message, #i = Content info. The user can combine some/all of these to construct the sentence that is spoken.

I encountered with two very tiny issues: In an Android 7 device all the widget modes are available, but e.g. the font of the clock widget does not scale when scaling the widget.  In an Android 11 deice the "Sun Position 4x2" widget (the rectangular world map) can not be had at all. When I paste it, it will be the round world in 4x3, it can be scaled, in 1x1 it shows the Altitude & Azimuth, in 2x2 it show the same as 1x1 but font does not enlarge, in 3x1 and in 4x1 and in 5x1 it shows the 'Sun Position 4x1" widget (night/day bar) and in that the content does scale properly.  In 4x4 and 5x5 it will be the round world map.

I'm so very happy I found Your app from F-Droid. It took many many hours for me to be able to post here. Now I'll engage into a fight with the masters of the interverse so that I can send a little something towards you.

Greetings form the frozen Finland!

### LINKED ISSUE #537: Feature Request: Custom Offset +- to Sunset
Actually i can see the Sunset Time according to Place+Civil/Nautical/Astronomical.
But i prefer to have an Offset like +1.5h after sunset and -1.5h before sunset based on civil time.

### LINKED ISSUE #551: Feature Request: Add cross-quarter day dates/times
Please consider adding the exact mid-points (cross-quarter days) between the soltices and equinoxes (aka Imbolc, Beltane, Lughnasadh and Samhain).

### LINKED ISSUE #552: Ephemeral notifications
Does Android allow notifications that disappear without needing to be dismissed?

If so, this would be a great little bonus. It's a small problem but really I just want to hear the notification - I already know what it is by the sound. Feels like a chore to always be dismissing notifications later.

Thanks so much for your work.

### LINKED ISSUE #572: Displays moon as 100%@0:08 for two consecutive nights
right now, March 17th  and 18th in central European winter time. Don't think that can be correct.. looks like time zone confusion?

Assuming the time means transit time there should not be any on the 17th.

### LINKED ISSUE #598: Custom sun elevation angle -event [Feature request]
Would be helpful at least for sunbathing purposes. One degree resolution would be well enough. Only one item would be needed in the event list, "custom sun angle". But needs additional value element with the qualifier option somewhere, or only the value element if "+" means ascending sun and "-" means descending sun.

A sunbather could then set an alarm to trigger at e.g. at 45° rising sun (usable UV level starts), with e.g. a 20 min before offset (driving time).

### LINKED ISSUE #601: sun position is out of alignment
**Describe the bug**
Ever since I've changed timezones (US eastcoast to central Europe) the daylight hours has been bumped over to the right (see screenshot). The sun is in the right position if the day below it was oriented correctly but it is skewed.

There is also a message on the main screen of the app which reads, "The time zone may be wrong for this location." I tap "SET TIME ZONE" and the one listed is correct so I tap "SET". The message is still at the bottom...

**To Reproduce**
1. Go to Europe
2. Sunposition graph changes but sun is in the right place.
3. delete widget and re-add, same behavior.

**Expected behavior**
adjust the graph based on local daylight hours.

**Screenshots**
Screenshot_20220515-132010
Screenshot_20220515-132133
Screenshot_20220515-132140

**Version Info:**
 - App Version: 0.14.4
 - Android Version: Android 8.1.0
 - Device Model: Palm PVG100

**Additional context**
thank you!!!

### LINKED ISSUE #603: First Time Install Experience
> I use this opportunity to explain my experience(s) about 1st time installation of the Suntimes, I've done a clean install well over ten times. In my opinion it is not overly smooth, to the extent that it possibly can rather easily upset a new user.  First one has to understand that it is the current location that needs to be specified. Then one has to find the Location dialog, where the default mode is "User Defined': Phoenix, but it can not be removed by the means provided in that dialog. Next one gets the bright idea to change the mode to 'Current (last known)', but unfortunately it does not help any. Then one may tap the 'update' textlink,  and it usually (as there is no gps fix indoors) just dismisses the Location dialog, which can be mind baffling.  So, is there not, inside the  Android somewhere, some kind of location data available to be used at the time of 1st install, just a coarse location (or network derived location) at this point would help a great deal. There surely is in Android the system time zone data. If these could be used automatically as the default setting for clean install, it would be way better for the 1st time user. My approach to this is to open the 'My Location' app by Mirfatif (from F-Droid), go outdoors, monitor the app until it show that gps fix has been achieved. Then switch back to Suntimes and update the gps location in the Location dialog, and finally go back indoors to continue settings.  I always set the 'GPS recent max age to 'any age' so after it is once got it never vanishes. 

_Originally posted by @Timo-Fi in https://github.com/forrestguice/SuntimesWidget/issues/601#issuecomment-1128066944_

### LINKED ISSUE #611: Confusing UX on alarm list
The UX on the alarms list is problematic.

Steps to reproduce:
1. Go to Suntimes Alarms
2. There is a list of alarms (or notifications): `00:30` `14:08` `20:22`
3. Tap `14:08` - it toggles to displaying `3 hours before 17:08`. Now the list shows alarms in confusingly different formats. It's not certain when the next alarm is.
4. Tap the alarm again to untoggle the different format - you get the alarm edit dialog instead. Cue frustration!

**Expected behavior**
A list of alarms should probably not show times in different formats simultaneously. Too confusing. Possible solution: a global toggle to show _all_ the alarms in `xx:xx` format or `x hours before xx:xx` format.

**Version Info:**
 - App Version: 0.14.5
 - Android Version: 8

### LINKED ISSUE #613: Sun/Moon Drop-downs show wrong data
**Describe the bug**
If the following location is different from current system location, time zone set match set location, and date to several months in the future, then the data in the Sun/Moon drop-downs is different to that in the main display:

**To Reproduce**
Set:
a. Location to somewhere in a different time zone (e.g. Athens)
b. Time zone to match the new location (Z+2, DST+1)
c. Date to 30/09/22

Data shown looks sane (but not easy to check).

BUT:
1) tap on Solar noon for **Sun Position** drop-down: data appears for current **system time/date** (and location?)
2) tap on Moon for **Moon** drop-down shows moon data consistent with that shown for **set date** (and location?), BUT sliding the date backwards or forwards a day at a time, the data in the Moon drop-down (which has no date!) doesn't change.
These two major and inconsistent defects call into question the reliability of all data shown by the app. 

**Expected behavior**
1) it's counter-intuitive to tap on Solar _Noon_ to get solar data for other times (sunrise, current, sunset). The Solar Data in the **Sun Position** drop-down should be for the Date, Time Zone and Location shown in the main display rather for System data!
2) the Lunar data in the **Moon** drop-down should be for the Date, Time Zone and Location shown in the main display and to inspire any confidence, the date and time must be shown in the drop-down.

**Screenshots**
N/A - posting on a laptop (too painful on tablet).

**Version Info:**
 - App Version: 0.14.6 (from F-Droid)
 - Android Version: 9
 - Device Model: Galaxy Tab S3 SM-T825

**Additional context**
I'm planning an evening photo-shoot on a Greek mountain in September, so I want to know local times (and bearings) of sunset, moon-rise and -set and moon-phase; so I want to select a week when: the sunset won't be behind another, taller, mountain; the moon will be between 1st and 3rd qtrs and will be high in the sky at sunset and on a bearing to give some background light and so that walking back down the mountain won't be in pitch dark!

### LINKED ISSUE #615: Mad defaults on install
I came very close to abandoning this as non functional after spending 10 minutes poking around trying to get it to display something close to the correct sunrise and sunset for my location.
The complete absence of help or guidance, the tiny font with colours that are almost unreadable in daylight, the confusing terminology around time zones, and the need to manually look up the coordinates for your location are all parts of the nightmare.
Please on install look up the current timezone and location from the system - hundreds of other apps manage this without problems.
Please increase the font size for the key info so it is more visible - the primary things are the time the sun and moon actually rise and set - and the direction. The other times may all be useful for particular purposes, but make them less prominent.
And pay attention to legibilty - orange text on black is not good, especially if the font is small. Black text of a sensible size on a white background.
By the way it is completely unclear what the point of the map icon is - it gives you an android dialogue to select which map app to use, but what is the point. When the map opens it doesnt seem to allow you to select a location and pass it back to this app to get the sunrise for the selected point - so why is it there?

### LINKED ISSUE #618: Alarm list sorting question (0.14.7)
Hello! I have the very same alarm list file imported to Suntimes in both OS7.0 and OS11 devices (I do know that OS11 is not a target device for Suntimes yet, I hope that extra info does not hurt). On both devices it is absolutely not possible to have it so that my 21 alarms would be listed in the order of Alarm Time **in such manner** that the next alarm would be seen topmost on the list.  Interestingly, sorting by Alarm Time does not result the same sort order of the list, between the devices.  The list will always be in order of Alarm Time, but not so that the next alarm would be topmost, there is always some or more alarms on top of the one that will fire next. Both devices have the same (automatic) settings in the OS setup, TZ=+2 and DST=+1.

This alarm list file was initially created using the first version that made it possible to export the list, and there after has been edited on both OS7 and OS11 devices, and using each of the more recent versions of Suntimes. I now updated to 0.14.7, then exported the list from OS11 device, and imported it to OS7 device. So, could it be that this sorting behavior is due to the history of my file,  and I need to create the list all over again from the scratch in case I want to see the expected result?  

This really is not a major concern, just a nice to have in the future. Also, it would be helpful to readily see how much time there still is until the alarms are fired, now one has to tap the individual alarm in order to see that info.  Could it be relocated to the place of "Everyday", with the "Everyday" being moved to the right side of that same line, immediately next to the loudspeaker icon?

### LINKED ISSUE #622: [Feature request] enlarge font size
Hi forrestguice,
first I want to say thank you: simple, clear screen design, handy and privacy friendly. I like the app.
I think it would be very helpful if I could change or enlarge the font size on the main screen (sunrise sunset).

### LINKED ISSUE #625: Findings after the summer season
Hi, I've been using the version 0.14.7 throughout the summer, here are some aspects I'd like to mention.

1)  On my cheapo devices the font size of the Sun Position 3x1 widget is so small that the information ("alt", "noon alt", etc) are difficult to discern when outdoors under bright daylight. The Sun Position -tool shows the same information at same/similar font size but mostly with bold font style, these I can read more easier, but still with some difficulty.  Except for the 2nd row, the time stamp row, that is not in bold font face. So, I'm hoping if they could have somewhat larger font size, or perhaps there could even be a new widget or a new layout, so that the current altitude angle of the sun could be shown at very large font size, like taking the whole area of a 2x1 widget or even at 4x2 size.

2) In the The Sun Position -tool, could it be possible, that a tap on the "Alt" (the current altitude angle of the sun)  would open an input dialog where one could enter a desired altitude angle, and the dialog would have two buttons named as "Rising" and "Setting" or such, either one would close the input dialog and then the output of the tool would be set according to that altitude? This would make it more easier to inspect a particular situation than using the animation function.  

3) A very minor plea... In the Sun Position 3x2 widget, could there be a new layout to show the altitude angle of the sun as a curve line on a chart?  X-axis as the time from -12h to +12h and Y-axis as the altitude angle from 0 to 90 degrees, with hairline divisions for both scales, and the path of the sun as a yellow curve line with the icon of sun at the current time. This would show a great overall info at a glance, and it would be a nice conversation feature, as by changing the Location -setting one could quickly compare the sunbathing conditions at different destinations. 

4) I have set one of the widgets to the perform: "On Tap: Update Widget" -action. I'm thinking if this could be changed to update all the existing widgets simultaneously, as the non-updated state never(?) is desirable.

5) In the Moon Widget (3x1) Major Phases (that I show in 4x1 size) the long month names (like September) push the time of the clock down to a new line,  so only the top half of that line is visible  in 4x1. When I allocate 4x2 then that line is visible but a lot of real estate is wasted.  Could the months be shown with their thee-first-letters abbreviation?     

6) Most likely I'm the only one with this, but anyway.... Could it be at all possible to have it so that the notifications that are iss7ued by the Suntimes would be acted upon by Android OS just like it happens now, but after that they would simply sink without a trace? This would allow notifications to run indefinitely. Currently the OS will stop notifications from an app when there are about 20 of them collected in the notification_shade and then the user has to remove them. So, I'd like to have a device running unattended on the wall, showing a nice screen with Sun Position Widget, Suntimes Widget, Moon Widget while it also speaks out the hourly notifications.  
 
Thank you so very much for the very best of the best apps,
Timo

### LINKED ISSUE #628: Various alarm issues
**Describe the bug**
1    I have set up multiple repeating alarms for Civil Twilight am and pm, both solstices and both equinoxes (see attached)  
Screenshot_20220930_100754_com forrestguice suntimeswidget

Sometimes, twice so far in about 5 days, I get a notification, as attached,
Screenshot_20220927_125144_eu faircode email
 warning me that the alarm is due in some hours.  The first time I swiped the notification (or possibly clicked dismiss) and the notification did disappear.  However the alarm also did not ring as I expected.

why do/did these notifications sometimes appear?

why does dismissing them remove that alarm? though maybe that was connected to the 2nd issue.

The 2nd time I got the notification warning I ignored it and it self disappeared and, I think, the next twilight pm alarm did not go off.

2  The last 4 civil twilight am and pm alarms have not rung at all.

The alarms are still showing but not activating at all.

They worked fine for first 6? events.

**To Reproduce**
Created twilight am and pm alarms on repeat every day (except Sunday for am)

**Expected behavior**
Expected alarm 

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Version Info:**
 - App Version:  0.14.7 9(just updated to  0.14.8 but no alarms due or rung since)
 - Android Version: 10
 - Device Model: Honor View 20

**Additional context**
Add any other information about the problem here.

### LINKED ISSUE #656: [Feature request] Accessibility issues in GUIs
**Description**
This is a feature request about components that have accessibility issues within the GUI of such an App.
Also, as the following Figure, this report focuses on the content GUI page in the App.
MuMu20221128085608
**Content**
After I applied my proposed tool to detect the content page, I discovered the text in this GUI could not be enlarged, which is hard for low-vision users to see clearly. So, I sincerely struggled you could repair these issues so that visually impaired users would use this App more conveniently.

### LINKED ISSUE #666: [Feature request] Set "system default" theme by default
Hi,
Please set the "system default" theme by default.

### PR DESCRIPTION
**Pull request by forrestguice**
* adds "Welcome Dialog"; a guided introduction and initial configuration wizard (closes #603).
* adds "High Contrast" app themes (#492, #615); changes default theme to "System default" (closes #666).
* adds "Text Size" setting; display "small", "normal", "large", or "extra-large" text (closes #492, closes #615, closes #622, closes #656).
* adds support for "Quick Settings" tiles; show information in the settings tray; "clock tile" and "next event tile" (closes #399).
* adds support for "Cross-Quarter Days" (closes #551); solstice and equinox midpoints.
* adds support for custom sun elevation events. Show custom events from a widget, or use them to schedule alarms and notifications (closes #522, closes #537, closes #598).
* adds "date" widget; show the date using different calendars (Coptic, Ethiopian, Gregorian, Hebrew, Julian, Solar Hijiri, Thai Solar) (closes #398); adds "date" option to clock widget (Gregorian).
* adds support for "Quick Notifications" (closes #552); notifications are automatically dismissed after a few moments.
* adds alarm "note"; show user-defined text as part of notifications and other UI; supports %s substitutions.
* adds alarm "snooze limit" option; defaults to "no limit".
* adds support for alarm challenges (and addons); dismiss alarms after solving "easy math" problems; dismiss alarms with an NFC tag (https://github.com/forrestguice/SuntimesNFC).
* adds alarm "reminder" option (closes #628), and "reminder action" option; notifications may perform a custom action when dismissed.
* increments alarm database version 3 -> 4; adds "note", "flags", "actionID2", and "actionID3" columns.
* enhances alarm cards; list UI now indicates state, animates sounding and snoozing states, and displays action buttons when applicable.
* adds alarm list sort options; "Enabled First", "Show Offsets" (closes #611, closes #618); adds "Clear Selection" button.
* adds "Altitude Graph" to Sun Position dialog; adds 3x2 "Altitude Graph" to sun position widgets (closes #625).
* adds "Seek Altitude" to Sun Position dialog (#625); jump to sunrise, sunset, noon, or user-defined sun elevation.
* changes the main card to display moon illumination as a range (closes #384, closes #572).
* adds Moon dialog playback controls; step forward/back by 5m increments.
* adds "lunar noon" and "lunar midnight" to Moon dialog; enhances rise/set view (swipe-able, seeks forward/back).
* adds "moon day" widget (closes #345); show number of days since the new moon.
* adds "Emphasize Field" to User Interface settings; enlarges text displayed by main table (#622, #615).
* removes "Set Date" dialog; replaced with "View Date" (#613); cards now seek to date instead of (re)centering.
* enhances solstice/equinox card (swipe-able, cross-quarter dates).
* adds 3x1 sun widget (#423); an expanded version of the 2x1 widget.
* adds "use app time zone" widget option.
* adds TimeZone dialog preview; replaces TimeZone dialog sort action mode with a context menu.
* misc dialog improvements; changes to Location, Date, and TimeZone dialog layouts.
* misc settings; "object shadow" moved from "General" to "User Interface".
* fixes bug "sun/moon drop-downs show wrong data" (closes #613).
* fixes bug "sun position is out of alignment" (closes #601).
* fixes bug where already enabled alarms fail to reschedule after modifying alarm details (#TODO).
* fixes tooltip help (now available for all buttons); press and hold to display help.

### CODE REVIEW

**Comment by forrestguice** [comment]
Adding code means adding bugs. 
I'm releasing `v0.15.0` as it is.

I think this could use more testing, but I'm running low on energy.. Time to recharge.
If I've missed something obvious (hope not), it can always be fixed in the next patch.

**Comment by jackthebean** [comment]
Great load of improvements.  Thanks for all the work.

**Comment by jackthebean** [comment]
Thanks for all the improvements.

However looking at below:

yJ0gRWXFqd0er8cu


I cannot work out what the marked bit shows and cannot see anywhere that describes it.

Also in the help page the descriptions are a bit unclear.   Clearer are those at 

[www.weather.gov](http://www.weather.gov/)

[Twilight Types](https://github.com/forrestguice/SuntimesWidget/pull/686#)

[🔗 https://www.weather.gov/lmk/twilight-types](https://www.weather.gov/lmk/twilight-types)

 which make it clearer that civil twilight is, for example, a period between 6 and 12 degrees below horizon rather than just at 6 degrees.

Good to have option to put back those timings eg nautical and astronomical twilights which have disappeared from the standard view.

Oddity:  When I tap on day length icon near bottom of default page it shows different days.  Today is 13th Feb and if I tap on it it shows data for 13th,  if I change main screen to 12th it still shows 13th, change main screen to 11th and tapping on day length bar bring up data for 11th.  Same if going into the future.  14th shows 13th and 15th shows 15th. 

See below

0y4PCsob1CHdFBUO

k3oYqJinBpNjhQ4J

QDagfwfDYmIMQ1ox

**Comment by forrestguice** [comment]
Hi. I was just about to tag the next patch, and saw this (normally responses aren't so quick ;)

> I cannot work out what the marked bit shows and cannot see anywhere that describes it.

`0.93 m` is the object height, `2.79 m` is the shadow length, and `2.07 m` is shadow length at noon. Click `: -> Object Shadow` to change the object height (or click that area). There should also be a line mentioning it from `: -> Help`.

> It would be good to have option to put back those timings eg nautical and astronomical twilights which have disappeared from the standard view.

These were removed from defaults after receiving some (blistering) criticism about the table being overcrowded. You can restore them from `Settings -> User Interface -> Nautical Twilight`, etc.

> which make it clearer that civil twilight is, for example, a period between 6 and 12 degrees below horizon rather than just at 6 degrees.

This is actually nautical twilight (6 to 12 degrees). In the morning, civil twilight begins at 6 degrees, and ends at sunrise (0), and vice versa in the evening (beings at sunset (0), ends at 6 degrees). The "note area" ("2h 11m until noon" (next to clock)) makes some attempt to clarify, by uses phrases "until civil twilight" in the morning, and "until end civil twilight" in the evening. Agreed it is still confusing if you aren't already familiar with the domain.

> Oddity: When I tap on day length icon near bottom of default page it shows different days. Today is 13th Feb and if I tap on it it shows data for 13th, if I change main screen to 12th it still shows 13th, change main screen to 11th and tapping on day length bar bring up data for 11th. Same if going into the future. 14th shows 13th and 15th shows 15th.

Good catch. This seems like something left over from the previous implementation - the "yestderday/today/tomorrow" are a special case (for a reason I can no longer remember) - they are passing the same date (today) when opening the dialog.

**Comment by forrestguice** [comment]
That "oddity" is something to be fixed with `v0.15.2`. 
We can expand the help too. It is intentionally brief, but another sentence wouldn't hurt. I needs to communicate that the morning times (rising times) indicate the start of twilight, while evening times indicate its end.

**Comment by forrestguice** [comment]
Reading this once more (because I rush sometimes)..

In that first screenshot, it indicates an infinite shadow, maybe a funny way of saying the sun is below the horizon.
That part of the dialog has been a bit of an undocumented feature for awhile. The help dialog (and the line explaining the icon) are recent additions.

**Comment by jackthebean** [comment]
As you say - a very quick response!

Sorry I may be being dim but what is the object that has a height of 0.93m? Is this just a ' an object 0.93m tall would have a shadow.....' ? Why 0.93m? Thought it might be exact imperial unit but isn't. Nothing about it on the help page.

Will try to write a version update for the help if that would be useful. And will get civil twilight right! 
Thanks for the rest.

**Comment by forrestguice** [comment]
> Is this just a ' an object 0.93m tall would have a shadow....

Yes, this - just some object. I think the most useful value is probably your own height. Units should be metric units by default, but this can be changed from `Settings -> General`.

> Why 0.93m?

I'm not sure, but I'm guessing at some point while exploring the UI the height slider was dragged. The default value should be 6ft (`~1.83 m`).

**Comment by jackthebean** [comment]
Pretty sure that I never changed the height slider but have now.  Thanks for the explanation.

**Pull request merged**
