### PR TITLE
update Dutch translation

### PR DESCRIPTION
**Pull request by Joppla**
first part

### CODE REVIEW

**Comment by forrestguice** [comment]
Thank you. 👍 

I usually allow two weeks to pass between patch releases. I'm going to tag `v0.13.8` on monday. I will leave this pull open until then. If you want to make additional commits and push them, they should appear here.

Also, I've turned on the CI for this branch - you should notice some commits will have a green check next to them (or a red x). If you click on this, and then "Artifacts", its now possible to download a debug apk (automatically generated). It might be helpful if you aren't building the app yourself.

**Review by Joppla — COMMENTED** [review]
it should be "integratie"

**Comment by Joppla** [comment]
> Thank you. +1
> 
> I usually allow two weeks to pass between patch releases. I'm going to tag `v0.13.8` on monday. I will leave this pull open until then. If you want to make additional commits and push them, they should appear here.
> 
> Also, I've turned on the CI for this branch - you should notice some commits will have a green check next to them (or a red x). If you click on this, and then "Artifacts", its now possible to download a debug apk (automatically generated). It might be helpful if you aren't building the app yourself.

Please, make your own plan, I will do the translation as fast as possible, but I'm limited in time and inspiration ;-).

**Comment by forrestguice** [comment]
I understand completely :) There's no rush, so do things at your own pace.

I just wanted to set expectations - that things usually occur over a span of weeks - the plan around here is "slow and steady".

**Pull request merged**
